' open surfdata/PCT_PFT.ctl'
' set mpdset hires'
' set grads off' 
' set x 210 216'
' set y 131 137'
' set z 14'
' set gxout grfill'
' d pct_pft'
' cbar'
' set string 1' 
' set gxout grid'
' d pct_pft'
' draw title Percetage of PFT type 13: C3 non-arctic grass'
' gxyat -x 1400 -y 1000 pct_pft_type_13.png'
